name: CI
on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Check lint
        run: yarn lint

  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup
      - name: Run unittests
        run: yarn test
      - name: Save coverage
        uses: actions/upload-artifact@v2
        with:
          name: lcov.info
          path: coverage/lcov.info

  sonarcloud:
    needs: [unittests]
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Execute sonar action
        uses: ./.github/actions/sonar_scan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: [lint, sonarcloud]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Run local action with latest tags
        uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-linkcheck: true
          use-mermaid: true
          use-toc: true
          use-opengh: true
      - name: Test mdBook binary
        run: mdbook --version
      - name: Test mdbook-linkcheck binary
        run: mdbook-linkcheck --version
      - name: Test mdbook-mermaid binary
        run: mdbook-mermaid --version
      - name: Test mdbook-toc binary
        run: mdbook-toc --version
      - name: Test mdbook-open-on-gh binary
        run: mdbook-open-on-gh --version
      - name: Add Change and commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "./dist --force"
          default_author: github_actions
          message: "chore: Generate dist files [skip ci]"

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup
      - name: Run Semantic Release
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
