name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check lint
        run: yarn lint
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unittests
        run: yarn test
  build:
    needs: [lint, unittests]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run local action wit latest tags
        uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-linkcheck: true
      - name: Test mdBook binary
        run: mdbook --version
      - name: Test mdbook-linkcheck binary
        run: mdbook-linkcheck --version
      - name: Add Change and commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "./dist --force"
          default_author: github_actions
          message: "chore: Generate dist files [skip ci]"
  release:
    needs: [build, sonarcloud]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Packages
        run: yarn install --frozen-lockfile
      - name: Build Step
        env:
          Test: ""
        run: yarn build
      - name: Run Semantic Release
        run: yarn semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
