name: PR Analysis
on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup
      - name: Check lint
        run: yarn lint

  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup
      - name: Run unittests
        run: yarn test
      - name: Save coverage
        uses: actions/upload-artifact@v2
        with:
          name: lcov.info
          path: coverage/lcov.info

  sonarcloud:
    needs: [unittests]
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Execute sonar action
        uses: ./.github/actions/sonar_scan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
