name: Test this action
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          mdbook-version: "~0.3.0"
          use-linkcheck: true
          linkcheck-version: "~0.7.0"
      - name: Test mdBook binary
        run: mdbook --version
      - name: Test mdbook-linkcheck
        run: mdbook-linkcheck --version
